#!/bin/sh

uci delete ucitrack.@luci_plugin_samba[-1] >/dev/null 2>&1
uci add ucitrack luci_plugin_samba >/dev/null 2>&1
uci set ucitrack.@luci_plugin_samba[-1].init=luci_plugin_samba >/dev/null 2>&1
uci commit ucitrack >/dev/null 2>&1