#!/bin/sh

uci delete ucitrack.@pod_samba[-1] >/dev/null 2>&1
uci add ucitrack pod_samba >/dev/null 2>&1
uci set ucitrack.@pod_samba[-1].init=pod_samba >/dev/null 2>&1
uci commit ucitrack >/dev/null 2>&1